image:
  registry: docker.io
  repository: bitnami/mongodb
  tag: 3.7.3
  pullPolicy: IfNotPresent
mongodbRootPassword: mongo
mongodbUsername: adil
mongodbPassword: LearnIBMcloudFree@0cost
mongodbDatabase: admin
serviceType: NodePort
persistence:
  enabled: true
  accessMode: ReadWriteMany
  size: 5Gi
  claimSize: 1Gi
  storageClass: ibmc-file-bronze
  billingType: hourly
  path: /innovate
resources:
  requests:
    memory: 512Mi
    cpu: 200m
